services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: sitloboi2012/vote-app:latest
    build:
      context: ./vote
    ports:
      - "8080:80"
    depends_on:
      - redis

  worker:
    image: sitloboi2012/worker-app:latest
    build:
      context: ./worker
    depends_on:
      - db
      - redis

  result:
    image: sitloboi2012/result-app:latest
    build:
      context: ./result
    ports:
      - "8081:80"
    depends_on:
      - db
